import type { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../src/app.module.js';
import { MailService } from '../src/common/mail/mail.service.js';
import { PrismaService } from '../src/prisma/prisma.service.js';
import { configureApp } from '../src/bootstrap.js';

describe('Auth Verification (e2e)', () => {
  let app: INestApplication;
  let prisma: PrismaService;
  let mailService: Partial<MailService>;

  const email = `verify_${Math.random().toString(36).slice(2)}@test.io`;
  const password = 'Password@123';
  let accessToken: string;
  let userId: string;

  beforeAll(async () => {
    mailService = {
      sendOtp: jest.fn().mockResolvedValue(undefined),
    };

    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    })
      .overrideProvider(MailService)
      .useValue(mailService)
      .compile();

    app = moduleRef.createNestApplication();
    configureApp(app);
    await app.init();

    prisma = app.get(PrismaService);

    // Create a user for testing
    const signup = await request(app.getHttpServer())
      .post('/api/auth/signup')
      .send({ email, password, displayName: 'Verify User' })
      .expect(201);

    accessToken = signup.body.accessToken;

    // Get user ID
    const me = await request(app.getHttpServer())
      .get('/api/me')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(200);

    userId = me.body.id;
  });

  afterAll(async () => {
    // Cleanup
    if (userId) {
      await prisma.user.delete({ where: { id: userId } });
    }
    await app.close();
  });

  it('POST /auth/send-verification', async () => {
    await request(app.getHttpServer())
      .post('/api/auth/send-verification')
      .set('Authorization', `Bearer ${accessToken}`)
      .expect(200);

    expect(mailService.sendOtp).toHaveBeenCalled();
  });

  it('POST /auth/verify-email (requires valid OTP)', async () => {
    // Since we mock sending, we can't easily get the REAL OTP generated by OtpService unless we spy on OtpService
    // But OtpService relies on Redis. In e2e, Redis is likely real.
    // We can't know the random OTP.
    // Strategy: We can verify the functionality with an invalid OTP,
    // OR we must access OtpService to 'peek' at the OTP, or just rely on 'send-verification-email' status 200.

    // Test invalid OTP
    await request(app.getHttpServer())
      .post('/api/auth/verify-email')
      .send({ email, otp: '000000' })
      .expect(401);
  });

  it('POST /auth/forgot-password', async () => {
    await request(app.getHttpServer())
      .post('/api/auth/forgot-password')
      .send({ email })
      .expect(200);

    expect(mailService.sendOtp).toHaveBeenCalled();
  });

  it('POST /auth/reset-password (invalid OTP)', async () => {
    await request(app.getHttpServer())
      .post('/api/auth/reset-password')
      .send({ email, otp: '000000', newPassword: 'NewPassword@123' })
      .expect(401);
  });
});
